# TX00DQ05-3001 Reinforcement Learning, exercises 1

In [32]:
# import numpy and other useful packages
import numpy as np
import numpy.linalg as LA
from random import randint

## Weather example

P is the transition matrix and t0 weather on day 0

In [3]:
P = np.array(([0.2, 0.8], [0.6, 0.4]))
t0 = np.array([0.0, 1.0])

t1 = np.dot(t0, P)
print(t1)
t2 = np.dot(t1, P)
print(t2)
print(np.dot(t0, LA.matrix_power(P, 2)))
print(np.dot(t0, LA.matrix_power(P, 10)))
print(np.dot(t0, LA.matrix_power(P, 30)))
print(np.dot(t0, LA.matrix_power(P, 50)))

[0.6 0.4]
[0.36 0.64]
[0.36 0.64]
[0.42852649 0.57147351]
[0.42857143 0.57142857]
[0.42857143 0.57142857]


## Exercise 1

Check some matrix algebra identities with numpy.

* A + B = B + A
* cA + cB = c(A + B) where c is scalar
* if shape of A is (x,y), shape of A.T (transpose) is (y,x) 
* if v is vector of shape (x,), then v dot A has shape (y,)
* verify that shape of A.T dot B is (y, y) and shape of A dot B.T is (x, x)

In [16]:
A = np.array(([1, 2, 3], [2, 0 ,2], [3, 0, 1], [4, 1 ,0]))
B = np.array(([0, 1, 2], [2, 1, 1], [2, 1, 0], [1, 2, 3]))



# 1) A + B = B + A
print("1)")
print(A + B)
print(B + A)

print("they are the same.")

# 2) cA + cB = c(A + B)
print("2)")
c = 4
print(c*A + c*B)
print(c*(A + B))
print("they are the same.")

# 3) if shape of A is (x,y), shape of A.T (transpose) is (y,x)
print("3)")
print(A.shape)
print(A.T.shape)

# 4) if v is vector of shape (x,), then v dot A has shape (y,)
print("4)")
v= np.array(([1,2,3, 4]))
print(v.shape)
print(v.dot(A).shape)

# 5) verify that shape of A.T dot B is (y, y) and shape of A dot B.T is (x, x)
print("5)")
print(B.shape)
print(A.T.dot(B).shape)

print(A.dot(B.T).shape)



1)
[[1 3 5]
 [4 1 3]
 [5 1 1]
 [5 3 3]]
[[1 3 5]
 [4 1 3]
 [5 1 1]
 [5 3 3]]
they are the same.
2)
[[ 4 12 20]
 [16  4 12]
 [20  4  4]
 [20 12 12]]
[[ 4 12 20]
 [16  4 12]
 [20  4  4]
 [20 12 12]]
they are the same.
3)
(4, 3)
(3, 4)
4)
(4,)
(3,)
5)
(4, 3)
(3, 3)
(4, 4)


## Exercise 2

Throw a dice (1..6) repeadetly and maintain the mean value of the 
numbers continously (and without explicitly storing the numbers or their sum) by
computing a correction factor to the previous mean.

Hint: mean(n) = sum(n) / n = (sum(n-1) + a(n)) / n = (mean(n-1) * (n-1) + a(n)) / n =
mean(n-1) + (a(n) - mean(n-1)) / n

Stop computation when correction factor stays below eps for b rounds or if you reach maxiter iterations.

How does changing eps and b influence the number of iterations needed?

In [239]:
eps = 0.00001
b = 50
maxiter = 1000000

# YOUR CODE HERE
x=1
y= randint(1, 6)

m = y

x=2
z=0

while (x <= maxiter):
    y= randint(1, 6)
    if (z >= b):
        break
    if ((y-m)/x < eps):
        z += 1
    m= m + (y-m)/x
    x += 1
    
print(m)
print(x)

# if you change eps bigger, you need less iterations. If you change b bigger, you need more iterations

3.4791666666666665
97


## Exercise 3

Given transition matrix P and initial state t0 write 
an iterative algorithm to find the steady state.

Stopping condition is that the norm (length of vector, use LA.norm) 
does not change more than eps in an iteration

In [95]:
maxiter = 10000
eps = 0.0000001

P = np.array(([0.2, 0.1, 0.7], [1.0, 0.0, 0.0], [0.2, 0.2, 0.6]))
t0 = np.array([1.0, 0.0, 0.0])




x = 1
y= np.dot(t0, LA.matrix_power(P, x))

x=2

for i in range(100000):
    z= y - np.dot(t0, LA.matrix_power(P, x))
    c=LA.norm(z)
    y= np.dot(t0, LA.matrix_power(P, x))
    x += 1
    if (c<=eps):
        break
        
print(x , "iterations and diff: " , int(c))
print(y)

15 iterations and diff:  0
[0.31249999 0.140625   0.54687501]
