# TX00DQ05-3001 Exercises 3

In [1]:
import numpy as np
import numpy.linalg as LA
from random import randint

## Exercise 1: Sample behaviour of an MDP

Let's take (again) a look at Sutton & Barto example 4.1 gridworld. On each iteration start at every (non-terminating) state and sample actions in succeeding states by selecting them from uniform distribution (each action - up, down, left, right - is equally probable). Run the episode until terminal state is encountered. Collect statistics to calculate average number of steps needed before completion for each start state. Should this number match with something you have seen earlier in the exercises?

In [11]:
# YOUR CODE
rows_count = 4
columns_count = 4
V = np.zeros((rows_count, columns_count))
terminating = [(0,0), (rows_count-1, columns_count-1)]

def valueFor(row, column, direction):
    if (direction == 'up'):
        if (row == 0):
            r1 = 0
            c1 = column
            
        else:
            r1 = row -1
            c1 = column
    if (direction == 'left'):
        if (column == 0):
            r1 = row
            c1 = 0
        else:
            r1 = row
            c1 = column -1
    if (direction == 'down'):
        if (row == 3):
            r1 = row
            c1 = column
        else:
            r1 = row +1
            c1 = column
    
    if (direction == 'right'):
        if (column == 3):
            r1 = row
            c1 = column
        else:
            r1 = row
            c1 = column + 1

    return (r1,c1)


for i in range(1000):
    for r in range(rows_count):
        for c in range (columns_count):
            row=r
            column=c
            steps=0
            while not (row, column) in terminating:

                x = randint(1, 4)

                if (x == 1):
                    a=valueFor(row,column, 'up')
                elif (x==2):
                    a= valueFor(row,column, 'down')
                elif (x==3):
                    a=valueFor(row,column, 'left')

                else:
                    a= valueFor(row,column, 'right')

                row = a[0]
                column = a[1]
                steps += 1
                
         # m= m + (steps-m)/y   
            V[r,c] += steps
    

with np.printoptions(precision=2):
    print(V/1000) 


[[ 0.   13.12 19.74 20.59]
 [14.51 17.11 19.82 19.18]
 [19.98 20.84 18.31 14.26]
 [21.86 20.36 13.76  0.  ]]


## Exercise 2: Monte Carlo state value function estimation. 

Calculate state-value function V for the gridworld of Sutton & Barto example 4.1 using first-visit or every-visit Monte Carlo policy evaluation (see for example page 92 of Sutton & Barto). Policy to be evaluated is the same as before; each action (up, down, left, right) is equally probable.  Action that would result in leaving the grid (for example moving up in top row) will leave state unchanged (but action has been taken). Gamma (discount factor) is assumed to be = 1, ie. no discounting.

Try out both exploring starts (see Sutton & Barto, p. 96) and fixed start points. Any difference?

Take a look at the value function you get when you run the algorithm multiple times (with fixed # of iterations). Any observations?

In [14]:
# YOUR CODE
rows_count = 4
columns_count = 4
V = np.zeros((rows_count, columns_count))
V_times = np.zeros((rows_count, columns_count))
terminating = [(0,0), (rows_count-1, columns_count-1)]

def valueFor(row, column, direction):
    if (direction == 'up'):
        if (row == 0):
            r1 = 0
            c1 = column
            
        else:
            r1 = row -1
            c1 = column
    if (direction == 'left'):
        if (column == 0):
            r1 = row
            c1 = 0
        else:
            r1 = row
            c1 = column -1
    if (direction == 'down'):
        if (row == 3):
            r1 = row
            c1 = column
        else:
            r1 = row +1
            c1 = column
    
    if (direction == 'right'):
        if (column == 3):
            r1 = row
            c1 = column
        else:
            r1 = row
            c1 = column + 1

    return (r1,c1)


for i in range(10000):
    #for rr in range(rows_count):  # fixed starts
       # for cc in range (columns_count):
         #   row=rr
          #  column=cc
           # steps=0
    rr= randint(0,3)  #each state has has a nonzero probability of being selected as the start (exlporing starts)
    cc = randint(0,3)
    steps=0
    row=rr
    column=cc
    while not (row, column) in terminating:

        x = randint(1, 4)

        if (x == 1):
            a=valueFor(row,column, 'up')
        elif (x==2):
            a= valueFor(row,column, 'down')
        elif (x==3):
            a=valueFor(row,column, 'left')

        else:
            a= valueFor(row,column, 'right')

        row = a[0]
        column = a[1]
        steps += -1

    V[rr,cc] += steps            # (if first-visit ´: check is the state occurred earlier in the episode)
    V_times[rr,cc] +=1           # how many times started from that state


with np.printoptions(precision=2):
    print(V/V_times)
    
#  with exploring starts:
#[[  0.   -14.4  -22.07 -22.1 ]
# [-13.36 -18.58 -19.61 -21.92]
# [-19.68 -20.49 -17.49 -13.74]
# [-23.42 -20.23 -14.13   0.  ]]

# with fixed starts:
#[[  0.   -13.9  -19.99 -22.04]
# [-14.5  -18.12 -20.1  -19.97]
# [-19.81 -20.31 -18.02 -13.72]
# [-22.07 -20.18 -14.02   0.  ]]

# --> I didn't notice any major differences

[[  0.   -14.57 -20.46 -21.35]
 [-14.56 -18.3  -19.43 -19.57]
 [-19.87 -20.41 -16.75 -13.81]
 [-22.69 -20.39 -14.06   0.  ]]
