# TX00DQ05-3001 Exercises 2

Note that you don't have to use the functions / other code in the cells below. They are there just in case you need inspiration to get started.

In [1]:
import numpy as np
print(np.__version__)
import numpy.linalg as LA

1.15.4


## Exercise 1: Iterative policy evaluation. 

Calculate state-value function V for the gridworld of Sutton & Barto example 4.1. Policy is assumed to be random, ie. each of the four directions are equally likely. Movement that would result in leaving the grid (for example moving up in top row) will leave state unchanged (but action has been taken). Gamma (discount factor) is assumed to be = 1, ie. no discounting.

When norm of the difference between new V and the old one is less than eps, stop iteration.

Compare needed number of iterations between synchronous (sweep over all states, and update value function after the sweep) and asynchronous (use always the latest values) update of state-value function.

Note that numpy tensor assignment does not create a copy. You might want to use .copy() method to avoid sharing a reference to the same array.

In [14]:
rows_count = 4
columns_count = 4
V = np.zeros((rows_count, columns_count))
V_new = np.zeros((rows_count, columns_count))
terminating = [(0,0), (rows_count-1, columns_count-1)]
stepcost = -1

maxiters = 1000
eps = 0.0000001

def valueFor(row, column, direction):
    if (direction == 'up'):
        if (row == 0):
            r = 0
            c = column
            
        else:
            r = row -1
            c = column
    if (direction == 'left'):
        if (column == 0):
            r = row
            c = 0
        else:
            r = row
            c = column -1
    if (direction == 'down'):
        if (row == 3):
            r = row
            c = column
        else:
            r = row +1
            c = column
    
    if (direction == 'right'):
        if (column == 3):
            r = row
            c = column
        else:
            r = row
            c = column + 1
            
    c = int(c)
    r = int(r)
    return V[r, c]

for i in range(maxiters):
    for r in range(4):
        for c in range(4):
            if (r == 0 and c == 0):
                V_new[0,0]= 0
            elif (r == 3 and c == 3):
                V_new[3,3]= 0
            
            else:   
                a = valueFor(r,c,'up')
                b = valueFor(r,c,'left')
                c1 = valueFor(r,c,'down')
                d = valueFor(r,c,'right')

                V_new[r,c] = 0.25*(a+stepcost+b+stepcost+c1+stepcost+d+stepcost)
            n += 1
        n = 0
        m += 1
    dd = V_new - V
    delta=LA.norm(dd)
    V = V_new.copy()
    if (delta < eps):
        break
    

print("iteration", i)
with np.printoptions(precision=3):
    print(V)

iteration 319
[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]


# Exercise 2: Greedy policy. 

Based on the state-value function computed in exercise 1, print out deterministic greedy policy function. Is the policy generated also optimal one?

In [55]:
# IT IS OPTIMAL


def valueFor(row, column, direction):
    if (direction == 'up'):
        if (row == 0):
            r = 0
            c = column
            
        else:
            r = row -1
            c = column
    if (direction == 'left'):
        if (column == 0):
            r = row
            c = 0
        else:
            r = row
            c = column -1
    if (direction == 'down'):
        if (row == 3):
            r = row
            c = column
        else:
            r = row +1
            c = column
    
    if (direction == 'right'):
        if (column == 3):
            r = row
            c = column
        else:
            r = row
            c = column + 1
            
    return V[r,c]

for r in range (4):
    for c in range (4):
        if (r==0 and c == 0):
            print('_', end=" ")
        elif (r==3 and c==3):
            print('_', end=" ")
        else:
                              
            a = valueFor(r,c,'up')
            b = valueFor(r,c,'left')
            c1 = valueFor(r,c,'down')
            d = valueFor(r,c,'right')
            mp = [a,b,c1,d]
            
            if(max(mp) == a):
                print('up', end=" ")
            elif (max(mp) == b):
                print('left', end=" ")
            elif (max(mp) == c1):
                print('down', end=" ")
            else:
                print('right', end=" ")
    print(' ')
                
            
                   

       

        





_ left left left  
up left left down  
up up down down  
right right right _  


## Exercise 3: Value function and policy in modified gridworld.

Change the definition of the exercise 1 gridworld by assigning a cost of -8 to movement in "up" direction. Compute the value function and greedy policy based on the value function. Is the greedy policy optimal?

In [56]:
# THE GREEDY POLICY IS OPTIMAL

rows_count = 4
columns_count = 4
V = np.zeros((rows_count, columns_count))
V_new = np.zeros((rows_count, columns_count))
terminating = [(0,0), (rows_count-1, columns_count-1)]
stepcost = -8

maxiters = 1000
eps = 0.0000001

def valueFor(row, column, direction):
    if (direction == 'up'):
        if (row == 0):
            r = 0
            c = column
            
        else:
            r = row -1
            c = column
    if (direction == 'left'):
        if (column == 0):
            r = row
            c = 0
        else:
            r = row
            c = column -1
    if (direction == 'down'):
        if (row == 3):
            r = row
            c = column
        else:
            r = row +1
            c = column
    
    if (direction == 'right'):
        if (column == 3):
            r = row
            c = column
        else:
            r = row
            c = column + 1
            
    c = int(c)
    r = int(r)
    return V[r, c]

for i in range(maxiters):
    for r in range(4):
        for c in range(4):
            if (r == 0 and c == 0):
                V_new[0,0]= 0
            elif (r == 3 and c == 3):
                V_new[3,3]= 0
            
            else:   
                a = valueFor(r,c,'up')
                b = valueFor(r,c,'left')
                c1 = valueFor(r,c,'down')
                d = valueFor(r,c,'right')

                V_new[r,c] = 0.25*(a+stepcost+b+stepcost+c1+stepcost+d+stepcost)
    dd = V_new - V
    delta=LA.norm(dd)
    V = V_new.copy()
    if (delta < eps):
        break
    

print("iteration", i)
with np.printoptions(precision=3):
    print(V)

for r in range (4):
    for c in range (4):
        if (r==0 and c == 0):
            print('_', end=" ")
        elif (r==3 and c==3):
            print('_', end=" ")
        else:
                              
            a = valueFor(r,c,'up')
            b = valueFor(r,c,'left')
            c1 = valueFor(r,c,'down')
            d = valueFor(r,c,'right')
            mp = [a,b,c1,d]
            
            if(max(mp) == a):
                print('up', end=" ")
            elif (max(mp) == b):
                print('left', end=" ")
            elif (max(mp) == c1):
                print('down', end=" ")
            else:
                print('right', end=" ")
    print(' ')

iteration 357
[[   0. -112. -160. -176.]
 [-112. -144. -160. -160.]
 [-160. -160. -144. -112.]
 [-176. -160. -112.    0.]]
_ left left left  
up left left down  
up up down down  
right right right _  


## Exercise 4: Value iteration

Solve the exercise 1 gridworld with value iteration algorithm. Solve also modified gridworld (cost of "up" movement = -4).

In [2]:
# koodissa on varmaan jotain vikaa, sillä en saanut toimimaan (cost of "up" -4)
# muunnoksen kanssa (suunnat eivät käyneet järkeen).

theta = 0.0001
maxiters = 10
rows_count = 4
columns_count = 4
V = np.zeros((rows_count,columns_count))
directions = ["up", "right", "left", "down"]
directions_new = []


# YOUR CODE HERE
#, (rows_count-1, columns_count-1)

V_new = np.zeros((rows_count, columns_count))
terminating = [(0,0), (rows_count-1, columns_count-1)]
stepcost = -1


def valueFor(row, column, direction):
    if (direction == 'up'):
        if (row == 0):
            r = 0
            c = column
            
        else:
            r = row -1
            c = column
    if (direction == 'left'):
        if (column == 0):
            r = row
            c = 0
        else:
            r = row
            c = column -1
    if (direction == 'down'):
        if (row == 3):
            r = row
            c = column
        else:
            r = row +1
            c = column
    
    if (direction == 'right'):
        if (column == 3):
            r = row
            c = column
        else:
            r = row
            c = column + 1

    return V[r, c]
for k in range(100000):
    for i in range(maxiters):
        for r in range(rows_count):
            for c in range(columns_count):
                if not (r, c) in terminating:
                   

                    a = valueFor(r,c,'up')
                    b = valueFor(r,c,'left')
                    c1 = valueFor(r,c,'down')
                    d = valueFor(r,c,'right')

                    V_new[r,c] = 0.25*(a+stepcost+b+stepcost+c1+stepcost+d+stepcost)
    dd = V_new - V
    delta=LA.norm(dd)
    if (delta < theta):
        break
    V = V_new.copy()

    directions_new.clear()
    row = 0
    column =0
    for row in range(rows_count):
        for column in range(columns_count):
            if not (row, column) in terminating:
                
                a = valueFor(row,column,'up')
                b = valueFor(row,column,'left')
                c1 = valueFor(row,column,'down')
                d = valueFor(row,column,'right')

                mp = [a,b,c1,d]
    
                if(max(mp) == a):
                    directions_new.append('up')
                elif (max(mp) == b):
                    directions_new.append('left')
                elif (max(mp) == c1):
                     directions_new.append('down')
                else:
                     directions_new.append('right')

    if (directions_new == directions):
       
        break
    directions = directions_new.copy()
    
print ('iterations: ', k)  
with np.printoptions(precision=3):
    print(V)      
print('_',directions[0],directions[1],directions[2])
print(directions[3],directions[4],directions[5],directions[6])
print(directions[7],directions[8],directions[9],directions[10])
print(directions[11],directions[12],directions[13],'_')


iterations:  3
[[ 0.    -3.062 -3.844 -3.969]
 [-3.062 -3.719 -3.906 -3.844]
 [-3.844 -3.906 -3.719 -3.062]
 [-3.969 -3.844 -3.062  0.   ]]
_ left left left
up up left down
up up down down
up right right _
